src/match/dtos/result-match.dto.ts
src/match/entities/match-result.entity.ts
src/match/entities/match.entity.ts
src/match/entities/team-stats.entity.ts
src/match/match.controller.ts
src/match/match.module.ts
src/match/match.service.ts

feat: 경기 세부조회, 팀 경기 일정 조회 추가

---

src/main.ts
src/member/entities/member.entity.ts
src/profile/entities/profile.entity.ts
src/team/entities/team.entity.ts

fix:프로필 entity 수정

---

src/match/entities/soccer-field.entity.ts
src/match/match.controller.ts
src/match/match.service.ts

fix:예약 api 수정, 예약 가능 시간 api 구현

fix:예약 api 수정, 예약 가능 시간 api 구현

---

src/match/dtos/result-match.dto.ts
src/match/entities/match-result.entity.ts
src/match/match.service.ts

fix:팀별 경기결과 수정(옐로우카드,클린시트)

---

src/match/match.controller.ts
src/match/match.service.ts

feat: 팀별 일정조회 추가

---

package-lock.json
package.json
src/app.module.ts
src/jobs/coordToAddr.ts
src/jobs/index.ts
src/jobs/jobs.controller.spec.ts
src/jobs/jobs.controller.ts
src/jobs/jobs.module.ts
src/jobs/jobs.service.spec.ts
src/jobs/jobs.service.ts
src/task/task.controller.ts
src/task/task.module.ts
src/task/task.service.ts

feat:경기장 API 조회 및 MYSQL 저장 구현

---

src/match/dtos/result-final.dto.ts
src/match/dtos/result-match.dto.ts
src/match/match.controller.ts
src/match/match.service.ts

fix: 경기 결과 입력 수정

---

src/formation/entities/formation.entity.ts
src/formation/formation.controller.ts
src/formation/formation.module.ts
src/formation/formation.service.ts
src/match/entities/match.entity.ts
src/match/match.module.ts
src/member/entities/member.entity.ts
src/team/entities/team.entity.ts
src/team/team.module.ts

fix:formation관련 import 경로 수정

---

src/formation/dtos/update-formation.dto.ts
src/formation/entities/formation.entity.ts
src/formation/formation.controller.ts
src/formation/formation.module.ts
src/formation/formation.service.ts
src/match/match.controller.ts
src/match/match.service.ts
src/member/member.controller.ts
src/member/member.service.ts

feat: 전술 조회, 저장 구현

---

src/chats/chats.controller.ts
src/chats/chats.gateway.ts
src/chats/chats.module.ts
src/chats/chats.service.ts
src/chats/dto/create-chat.dto.ts
src/chats/dto/enter-chat.dto.ts
src/chats/entities/chats.entity.ts
src/member/member.controller.ts
src/member/member.module.ts
src/member/member.service.ts
src/messages/dto/create-message.dto.ts
src/messages/dto/paginate-message.dto.ts
src/messages/messages.controller.ts
src/messages/messages.service.ts
src/team/entities/team.entity.ts
src/team/team.module.ts
src/team/team.service.ts
src/user/user.service.ts

- 팀에 초대되거나 , 속할 시 팀 전용 채팅방으로 들어가도록 변경
- 팀 엔티티 변경

feat: 채팅 수정

---

package.json
src/match/match.service.ts
test/match/app.match-spec.ts
test/match/formation.ts
test/match/jest-match.json

 feat: 경기결과 테스트 코드 작성

---

package-lock.json
src/app.module.ts
src/formation/formation.controller.ts
src/formation/formation.service.ts
src/match/match.controller.ts
src/match/match.service.ts

Feat/formation
fix: 팀결과 저장시 교체체크 제외

fix: 팀결과 저장시 교체체크 제외

---

package-lock.json
package.json
src/match/match.controller.ts

fix: 포메이션 페이지 선수명단 api 수정

---

src/auth/auth.service.ts
src/match/match.controller.ts
src/match/match.service.ts

feat:경기 결과 보기

---

src/formation/formation.service.ts

fix: 3경기간 누적 경고자 조회 수정

---

src/soccerfield/dtos/paginate-field-dto.ts
src/soccerfield/soccerfield.controller.ts
src/soccerfield/soccerfield.module.ts
src/soccerfield/soccerfield.service.ts

feat:경기장 조회 페이지네이션 적용

---

src/profile/profile.service.ts

fix: 프로필 저장 수정

---

src/match/match.controller.ts
test/match/app.match-spec.ts

fix:경기 수락시 메시지 수정

---

package.json
src/formation/formation.service.spec.ts
src/formation/formation.service.ts
src/match/match.service.spec.ts

feat: 포메이션 테스트 코드 작성 중

---

src/formation/formation.service.spec.ts

fix:포메이션 테스트 코드 수정

---

src/formation/formation.controller.spec.ts
src/match/match.service.ts

fix: 이메일 전송 로그 추가

---

src/match/match.controller.spec.ts
src/match/match.service.spec.ts
src/match/match.service.ts

fix: match.service 테스트 코드 수정

---

src/formation/formation.service.ts
src/match/match.service.ts

fix: 전술설정 조회시 팀 탈퇴자 제외

---

src/jobs/jobs.service.spec.ts
src/jobs/jobs.service.ts
src/match/match.service.spec.ts
src/redis/redis.service.spec.ts
src/soccerfield/soccerfield.service.spec.ts

fix: 테스트 코드 추가 수정 (jobs,redis,soccerfield)

fix:테스트 코드 추가 수정

---

src/formation/formation.service.ts
src/jobs/jobs.service.ts
src/match/match.controller.ts
src/match/match.service.ts
src/soccerfield/soccerfield.controller.ts
src/soccerfield/soccerfield.service.ts
src/task/task.service.ts

refactor: 불필요한 console.log 정리
